2019-01-19 13:27:29.804 [info] <0.43.0> Application lager started on node nonode@nohost
2019-01-19 13:27:29.851 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-01-19 13:27:29.882 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-01-19 13:27:30.014 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-01-19 13:27:30.029 [info] <0.43.0> Application ranch_proxy_protocol started on node nonode@nohost
2019-01-19 13:27:30.060 [info] <0.43.0> Application recon started on node nonode@nohost
2019-01-19 13:27:30.060 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-01-19 13:27:30.107 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-01-19 13:27:30.107 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-01-19 13:27:30.154 [info] <0.43.0> Application connection started on node nonode@nohost
2019-01-19 13:27:30.217 [info] <0.43.0> Application db_connection started on node nonode@nohost
2019-01-19 13:27:30.264 [info] <0.43.0> Application mongodb started on node nonode@nohost
2019-01-19 13:27:30.295 [info] <0.43.0> Application poolboy started on node nonode@nohost
2019-01-19 13:27:30.326 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-01-19 13:27:30.357 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-01-19 13:27:30.389 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-01-19 13:27:30.519 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-01-19 13:27:30.519 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-01-19 13:27:30.534 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-01-19 13:28:33.125 [info] <0.43.0> Application lager started on node nonode@nohost
2019-01-19 13:28:33.156 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-01-19 13:28:33.187 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-01-19 13:28:33.219 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-01-19 13:28:33.250 [info] <0.43.0> Application ranch_proxy_protocol started on node nonode@nohost
2019-01-19 13:28:33.266 [info] <0.43.0> Application recon started on node nonode@nohost
2019-01-19 13:28:33.266 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-01-19 13:28:33.281 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-01-19 13:28:33.281 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-01-19 13:28:33.328 [info] <0.43.0> Application connection started on node nonode@nohost
2019-01-19 13:28:33.359 [info] <0.43.0> Application db_connection started on node nonode@nohost
2019-01-19 13:28:33.391 [info] <0.43.0> Application mongodb started on node nonode@nohost
2019-01-19 13:28:33.422 [info] <0.43.0> Application poolboy started on node nonode@nohost
2019-01-19 13:28:33.453 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-01-19 13:28:33.453 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-01-19 13:28:33.484 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-01-19 13:28:33.516 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-01-19 13:28:33.516 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-01-19 13:28:33.531 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-01-19 13:28:33.922 [warning] <0.318.0> Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
2019-01-19 13:28:35.003 [warning] <0.246.0> lager_error_logger_h dropped 99 messages in the last second that exceeded the limit of 50 messages/sec
2019-01-19 13:29:12.007 [error] <0.426.0> Ranch listener 'Elixir.ControllstationWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {error,selection_timeout}},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reverse,1,[{file,"lib/enum.ex"},{line,2979}]},{'Elixir.Enum',to_list,1,[{file,"lib/enum.ex"},{line,2613}]},{'Elixir.ControllstationWeb.PageController',index,2,[{file,"lib/controlls..."},...]},...]},...}
2019-01-19 13:29:39.417 [error] <0.434.0> Ranch listener 'Elixir.ControllstationWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {error,selection_timeout}},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reverse,1,[{file,"lib/enum.ex"},{line,2979}]},{'Elixir.Enum',to_list,1,[{file,"lib/enum.ex"},{line,2613}]},{'Elixir.ControllstationWeb.PageController',index,2,[{file,"lib/controlls..."},...]},...]},...}
2019-01-19 13:29:43.702 [error] <0.433.0> Ranch listener 'Elixir.ControllstationWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {error,selection_timeout}},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reverse,1,[{file,"lib/enum.ex"},{line,2979}]},{'Elixir.Enum',to_list,1,[{file,"lib/enum.ex"},{line,2613}]},{'Elixir.ControllstationWeb.PageController',index,2,[{file,"lib/controlls..."},...]},...]},...}
2019-01-19 13:29:47.036 [error] <0.439.0> Ranch listener 'Elixir.ControllstationWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {error,selection_timeout}},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reverse,1,[{file,"lib/enum.ex"},{line,2979}]},{'Elixir.Enum',to_list,1,[{file,"lib/enum.ex"},{line,2613}]},{'Elixir.ControllstationWeb.PageController',index,2,[{file,"lib/controlls..."},...]},...]},...}
2019-01-19 13:58:39.013 [warning] <0.246.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2019-01-19 14:18:45.331 [error] <0.60.0> Supervisor {<0.60.0>,user_sup} had child at module user_sup at <0.61.0> exit with reason einval in context child_terminated
2019-01-19 14:18:45.331 [error] <0.60.0> gen_server <0.60.0> terminated with reason: einval
2019-01-19 14:18:45.333 [error] <0.60.0> CRASH REPORT Process <0.60.0> with 0 neighbours exited with reason: einval in gen_server:handle_common_reply/8 line 751
2019-01-19 14:18:45.333 [error] <0.48.0> Supervisor kernel_sup had child user started with user_sup:start() at <0.60.0> exit with reason einval in context child_terminated
2019-01-19 14:18:45.368 [error] <0.210.0> gen_event 'Elixir.Logger.Backends.Console' installed in 'Elixir.Logger' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"no device registered with the name :user">>} in 'Elixir.Logger.Backends.Console':async_io/2 line 160
2019-01-19 14:18:45.480 [error] <0.213.0> gen_server <0.213.0> terminated with reason: {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"no device registered with the name :user">>},[{'Elixir.Logger.Backends.Console',async_io,2,[{file,"lib/logger/backends/console.ex"},{line,160}]},{'Elixir.Logger.Backends.Console',log_event,5,[{file,"lib/logger/backends/console.ex"},{line,145}]},{'Elixir.Logger.Backends.Console',handle_event,2,[{file,"lib/logger/backends/console.ex"},{line,49}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,577}]},...]}}
2019-01-19 14:18:45.482 [error] <0.213.0> CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"no device registered with the name :user">>},[{'Elixir.Logger.Backends.Console',async_io,2,[{file,"lib/logger/backends/console.ex"},{line,160}]},{'Elixir.Logger.Backends.Console',log_event,5,[{file,"lib/logger/backends/console.ex"},{line,145}]},{'Elixir.Logger.Backends.Console',handle_event,2,[{file,"lib/logger/backends/console.ex"},{line,49}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,577}]},...]}} in gen_server:handle_common_reply/8 line 751
2019-01-19 14:18:45.482 [error] <0.58.0> Supervisor standard_error_sup had child at module standard_error at <0.59.0> exit with reason einval in context child_terminated
2019-01-19 14:18:45.482 [error] <0.58.0> gen_server standard_error_sup terminated with reason: einval
2019-01-19 14:18:45.482 [error] <0.58.0> CRASH REPORT Process standard_error_sup with 0 neighbours exited with reason: einval in gen_server:handle_common_reply/8 line 751
2019-01-19 14:18:45.483 [error] <0.212.0> Supervisor 'Elixir.Logger.WatcherSupervisor' had child {'Elixir.Logger.WatcherSupervisor',
    {'Elixir.Logger','Elixir.Logger.Backends.Console'}} started with 'Elixir.Logger.Watcher':start_link({'Elixir.Logger','Elixir.Logger.Backends.Console',console}) at <0.213.0> exit with reason {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"no device registered with the name :user">>},[{'Elixir.Logger.Backends.Console',async_io,2,[{file,"lib/logger/backends/console.ex"},{line,160}]},{'Elixir.Logger.Backends.Console',log_event,5,[{file,"lib/logger/backends/console.ex"},{line,145}]},{'Elixir.Logger.Backends.Console',handle_event,2,[{file,"lib/logger/backends/console.ex"},{line,49}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,577}]},...]}} in context child_terminated
2019-01-19 14:18:45.484 [error] <0.48.0> Supervisor kernel_sup had child standard_error started with standard_error:start_link() at <0.58.0> exit with reason einval in context child_terminated
2019-01-19 14:18:45.532 [error] <0.233.0>@lager_console_backend:handle_event:179 gen_event lager_console_backend installed in lager_event terminated with reason: bad argument in call to io:put_chars(user, unicode, [["14",58,"18",58,"45",46,"331"]," ",[],"[","error","] ",[83,117,112,101,114,118,105,115,111,114,...],...]) in lager_console_backend:handle_event/2 line 179
2019-01-19 14:18:45.563 [error] <0.238.0> Lager event handler lager_console_backend exited with reason {'EXIT',{badarg,[{io,put_chars,[user,unicode,[["14",58,"18",58,"45",46,"331"]," ",[],"[","error","] ",[83,117,112,101,114,118,105,115,111,114,32,"{<0.60.0>,user_sup}",32,104,97,100,32,99,104,105,108,100,32,"at module user_sup at <0.61.0>",32,101,120,105,116,32,119,105,116,104,32,114,101,97,115,111,110,32,"einval",32,105,110,32,99,111,110,116,101,120,116,32,"child_terminated"],"\r\n"]],[]},{lager_console_backend,handle_event,2,[{file,"f:/fajne rzeczy/phoenix/controllstation/deps/lager/src/lage..."},...]},...]}}
